// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace tflite
{

using global::System;
using global::FlatBuffers;

public struct OperatorCode : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_11_1(); }
  public static OperatorCode GetRootAsOperatorCode(ByteBuffer _bb) { return GetRootAsOperatorCode(_bb, new OperatorCode()); }
  public static OperatorCode GetRootAsOperatorCode(ByteBuffer _bb, OperatorCode obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public OperatorCode __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public tflite.BuiltinOperator BuiltinCode { get { int o = __p.__offset(4); return o != 0 ? (tflite.BuiltinOperator)__p.bb.GetSbyte(o + __p.bb_pos) : tflite.BuiltinOperator.ADD; } }
  public string CustomCode { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetCustomCodeBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetCustomCodeBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetCustomCodeArray() { return __p.__vector_as_array<byte>(6); }
  public int Version { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)1; } }

  public static Offset<tflite.OperatorCode> CreateOperatorCode(FlatBufferBuilder builder,
      tflite.BuiltinOperator builtin_code = tflite.BuiltinOperator.ADD,
      StringOffset custom_codeOffset = default(StringOffset),
      int version = 1) {
    builder.StartTable(3);
    OperatorCode.AddVersion(builder, version);
    OperatorCode.AddCustomCode(builder, custom_codeOffset);
    OperatorCode.AddBuiltinCode(builder, builtin_code);
    return OperatorCode.EndOperatorCode(builder);
  }

  public static void StartOperatorCode(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddBuiltinCode(FlatBufferBuilder builder, tflite.BuiltinOperator builtinCode) { builder.AddSbyte(0, (sbyte)builtinCode, 0); }
  public static void AddCustomCode(FlatBufferBuilder builder, StringOffset customCodeOffset) { builder.AddOffset(1, customCodeOffset.Value, 0); }
  public static void AddVersion(FlatBufferBuilder builder, int version) { builder.AddInt(2, version, 1); }
  public static Offset<tflite.OperatorCode> EndOperatorCode(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<tflite.OperatorCode>(o);
  }
};


}
