// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace tflite
{

using global::System;
using global::FlatBuffers;

public struct ResizeBilinearOptions : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_11_1(); }
  public static ResizeBilinearOptions GetRootAsResizeBilinearOptions(ByteBuffer _bb) { return GetRootAsResizeBilinearOptions(_bb, new ResizeBilinearOptions()); }
  public static ResizeBilinearOptions GetRootAsResizeBilinearOptions(ByteBuffer _bb, ResizeBilinearOptions obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ResizeBilinearOptions __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public bool AlignCorners { get { int o = __p.__offset(8); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<tflite.ResizeBilinearOptions> CreateResizeBilinearOptions(FlatBufferBuilder builder,
      bool align_corners = false) {
    builder.StartTable(3);
    ResizeBilinearOptions.AddAlignCorners(builder, align_corners);
    return ResizeBilinearOptions.EndResizeBilinearOptions(builder);
  }

  public static void StartResizeBilinearOptions(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddAlignCorners(FlatBufferBuilder builder, bool alignCorners) { builder.AddBool(2, alignCorners, false); }
  public static Offset<tflite.ResizeBilinearOptions> EndResizeBilinearOptions(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<tflite.ResizeBilinearOptions>(o);
  }
};


}
