// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace tflite
{

using global::System;
using global::FlatBuffers;

public struct ResizeNearestNeighborOptions : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_11_1(); }
  public static ResizeNearestNeighborOptions GetRootAsResizeNearestNeighborOptions(ByteBuffer _bb) { return GetRootAsResizeNearestNeighborOptions(_bb, new ResizeNearestNeighborOptions()); }
  public static ResizeNearestNeighborOptions GetRootAsResizeNearestNeighborOptions(ByteBuffer _bb, ResizeNearestNeighborOptions obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ResizeNearestNeighborOptions __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public bool AlignCorners { get { int o = __p.__offset(4); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<tflite.ResizeNearestNeighborOptions> CreateResizeNearestNeighborOptions(FlatBufferBuilder builder,
      bool align_corners = false) {
    builder.StartTable(1);
    ResizeNearestNeighborOptions.AddAlignCorners(builder, align_corners);
    return ResizeNearestNeighborOptions.EndResizeNearestNeighborOptions(builder);
  }

  public static void StartResizeNearestNeighborOptions(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddAlignCorners(FlatBufferBuilder builder, bool alignCorners) { builder.AddBool(0, alignCorners, false); }
  public static Offset<tflite.ResizeNearestNeighborOptions> EndResizeNearestNeighborOptions(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<tflite.ResizeNearestNeighborOptions>(o);
  }
};


}
